<?php

//Permissions for the add or renew user page
$_PERMISSIONS["HOME"]["EVERYONE"] = false;
$_PERMISSIONS["HOME"]["MEMBER"] = true;
$_PERMISSIONS["HOME"]["ADMIN"] = true;
$_PERMISSIONS["HOME"]["USERMANAGER"] = true;
$_PERMISSIONS["HOME"]["AUTHORIZEDBROWSERMANAGER"] = true;
$_PERMISSIONS["HOME"]["ADDRENEWUSERBROWSER"] = false;
$_PERMISSIONS["HOME"]["CHECKINBROWSER"] = false;

//Permissions for the add or renew user page
$_PERMISSIONS["ADDORRENEWUSER"]["EVERYONE"] = false;
$_PERMISSIONS["ADDORRENEWUSER"]["MEMBER"] = false;
$_PERMISSIONS["ADDORRENEWUSER"]["ADMIN"] = false;
$_PERMISSIONS["ADDORRENEWUSER"]["USERMANAGER"] = false;
$_PERMISSIONS["ADDORRENEWUSER"]["AUTHORIZEDBROWSERMANAGER"] = false;
$_PERMISSIONS["ADDORRENEWUSER"]["ADDRENEWUSERBROWSER"] = true;
$_PERMISSIONS["ADDORRENEWUSER"]["CHECKINBROWSER"] = false;

//Permissions for the add user page
$_PERMISSIONS["ADDUSER"]["EVERYONE"] = false;
$_PERMISSIONS["ADDUSER"]["MEMBER"] = false;
$_PERMISSIONS["ADDUSER"]["ADMIN"] = false;
$_PERMISSIONS["ADDUSER"]["USERMANAGER"] = false;
$_PERMISSIONS["ADDUSER"]["AUTHORIZEDBROWSERMANAGER"] = false;
$_PERMISSIONS["ADDUSER"]["ADDRENEWUSERBROWSER"] = true;
$_PERMISSIONS["ADDUSER"]["CHECKINBROWSER"] = false;

//Permissions for the renew user page
$_PERMISSIONS["RENEWUSER"]["EVERYONE"] = false;
$_PERMISSIONS["RENEWUSER"]["MEMBER"] = false;
$_PERMISSIONS["RENEWUSER"]["ADMIN"] = false;
$_PERMISSIONS["RENEWUSER"]["USERMANAGER"] = false;
$_PERMISSIONS["RENEWUSER"]["AUTHORIZEDBROWSERMANAGER"] = false;
$_PERMISSIONS["RENEWUSER"]["ADDRENEWUSERBROWSER"] = true;
$_PERMISSIONS["RENEWUSER"]["CHECKINBROWSER"] = false;

//Permissions for the authorized browser manager page
$_PERMISSIONS["AUTHORIZEDBROWSERMANAGER"]["EVERYONE"] = false;
$_PERMISSIONS["AUTHORIZEDBROWSERMANAGER"]["MEMBER"] = false;
$_PERMISSIONS["AUTHORIZEDBROWSERMANAGER"]["ADMIN"] = true;
$_PERMISSIONS["AUTHORIZEDBROWSERMANAGER"]["USERMANAGER"] = false;
$_PERMISSIONS["AUTHORIZEDBROWSERMANAGER"]["AUTHORIZEDBROWSERMANAGER"] = false;
$_PERMISSIONS["AUTHORIZEDBROWSERMANAGER"]["ADDRENEWUSERBROWSER"] = false;
$_PERMISSIONS["AUTHORIZEDBROWSERMANAGER"]["CHECKINBROWSER"] = false;

//Permissions for the change password page
$_PERMISSIONS["CHANGEPASSWORD"]["EVERYONE"] = false;
$_PERMISSIONS["CHANGEPASSWORD"]["MEMBER"] = true;
$_PERMISSIONS["CHANGEPASSWORD"]["ADMIN"] = true;
$_PERMISSIONS["CHANGEPASSWORD"]["USERMANAGER"] = true;
$_PERMISSIONS["CHANGEPASSWORD"]["AUTHORIZEDBROWSERMANAGER"] = true;
$_PERMISSIONS["CHANGEPASSWORD"]["ADDRENEWUSERBROWSER"] = false;
$_PERMISSIONS["CHANGEPASSWORD"]["CHECKINBROWSER"] = false;

//Permissions for the check in page
$_PERMISSIONS["CHECKIN"]["EVERYONE"] = false;
$_PERMISSIONS["CHECKIN"]["MEMBER"] = false;
$_PERMISSIONS["CHECKIN"]["ADMIN"] = false;
$_PERMISSIONS["CHECKIN"]["USERMANAGER"] = false;
$_PERMISSIONS["CHECKIN"]["AUTHORIZEDBROWSERMANAGER"] = false;
$_PERMISSIONS["CHECKIN"]["ADDRENEWUSERBROWSER"] = false;
$_PERMISSIONS["CHECKIN"]["CHECKINBROWSER"] = true;

//Permissions for the hint image manager page
$_PERMISSIONS["HINTIMAGEMANAGER"]["EVERYONE"] = false;
$_PERMISSIONS["HINTIMAGEMANAGER"]["MEMBER"] = false;
$_PERMISSIONS["HINTIMAGEMANAGER"]["ADMIN"] = true;
$_PERMISSIONS["HINTIMAGEMANAGER"]["USERMANAGER"] = false;
$_PERMISSIONS["HINTIMAGEMANAGER"]["AUTHORIZEDBROWSERMANAGER"] = false;
$_PERMISSIONS["HINTIMAGEMANAGER"]["ADDRENEWUSERBROWSER"] = false;
$_PERMISSIONS["HINTIMAGEMANAGER"]["CHECKINBROWSER"] = false;

//Permissions for the logout page
$_PERMISSIONS["LOGOUT"]["EVERYONE"] = true;
$_PERMISSIONS["LOGOUT"]["MEMBER"] = true;
$_PERMISSIONS["LOGOUT"]["ADMIN"] = true;
$_PERMISSIONS["LOGOUT"]["USERMANAGER"] = true;
$_PERMISSIONS["LOGOUT"]["AUTHORIZEDBROWSERMANAGER"] = true;
$_PERMISSIONS["LOGOUT"]["ADDRENEWUSERBROWSER"] = true;
$_PERMISSIONS["LOGOUT"]["CHECKINBROWSER"] = true;

//Permissions for the profile page
$_PERMISSIONS["PROFILE"]["EVERYONE"] = false;
$_PERMISSIONS["PROFILE"]["MEMBER"] = true;
$_PERMISSIONS["PROFILE"]["ADMIN"] = true;
$_PERMISSIONS["PROFILE"]["USERMANAGER"] = true;
$_PERMISSIONS["PROFILE"]["AUTHORIZEDBROWSERMANAGER"] = true;
$_PERMISSIONS["PROFILE"]["ADDRENEWUSERBROWSER"] = false;
$_PERMISSIONS["PROFILE"]["CHECKINBROWSER"] = false;

//Permissions for the reset password page
$_PERMISSIONS["PROFILE"]["EVERYONE"] = true;
$_PERMISSIONS["PROFILE"]["MEMBER"] = true;
$_PERMISSIONS["PROFILE"]["ADMIN"] = true;
$_PERMISSIONS["PROFILE"]["USERMANAGER"] = true;
$_PERMISSIONS["PROFILE"]["AUTHORIZEDBROWSERMANAGER"] = true;
$_PERMISSIONS["PROFILE"]["ADDRENEWUSERBROWSER"] = true;
$_PERMISSIONS["PROFILE"]["CHECKINBROWSER"] = true;

//Permissions for the user manager page
$_PERMISSIONS["USERMANAGER"]["EVERYONE"] = false;
$_PERMISSIONS["USERMANAGER"]["MEMBER"] = false;
$_PERMISSIONS["USERMANAGER"]["ADMIN"] = true;
$_PERMISSIONS["USERMANAGER"]["USERMANAGER"] = true;
$_PERMISSIONS["USERMANAGER"]["AUTHORIZEDBROWSERMANAGER"] = false;
$_PERMISSIONS["USERMANAGER"]["ADDRENEWUSERBROWSER"] = false;
$_PERMISSIONS["USERMANAGER"]["CHECKINBROWSER"] = false;
